version: '3'

services:
  gobooks-api:
    build: .
    ports:
      - "8080:8080"
    container_name: gobooks-api
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    container_name: db
